type: fields
fields:
  form_success_type:
    type: toggles
    label:
      *: arnoson.kirby-forms.success-type
    width: 5/12
    default: message
    options:
      - value: message
        text:
          *: arnoson.kirby-forms.message
        icon: text
      - value: page
        text:
          *: arnoson.kirby-forms.page
        icon: page
  form_success_message:
    type: writer
    label:
      *: arnoson.kirby-forms.message
    default: Thank you for the registration!
    width: 7/12
    when:
      form_success_type: message
  form_success_page:
    label:
      *: arnoson.kirby-forms.page
    type: pages
    multiple: false
    width: 7/12
    when:
      form_success_type: page
  form_submit_label:
    type: text
    default: Submit
    label:
      *: arnoson.kirby-forms.submit-button
  form_fields_error_message:
    type: writer
    label:
      *: arnoson.kirby-forms.error-message
    default: Please fill in all fields correctly.
