type: fields
fields:
  form_success_type:
    type: toggle
    label: Success
    width: 5/12
    text:
      - 'Message'
      - 'Page'
  form_success_message:
    type: writer
    label: Message
    default: Thank you for the registration!
    width: 7/12
    when:
      form_success_type: false
  form_success_page:
    label: Page
    type: pages
    multiple: false
    width: 2/3
    when:
      form_success_type: true
  form_fields_error_message:
    type: writer
    label: Fields Error
    default: Please fill in all fields correctly.
